---
- name: install ZNC
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - znc
    - znc-mod-nickserv


- name: configure ZNC
  template:
    src: znc.j2
    dest: /etc/config/znc
    owner: root
    group: root
    mode: 0600

- name: enable service
  openwrt_init:
    name: znc
    state: restarted
    enabled: yes
